#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = -Wall -fexceptions
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_RELEASE = $(INC) -Iinclude
CFLAGS_RELEASE = $(CFLAGS) -O2 -std=c++11 -Wfatal-errors -Wextra
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s -lboost_system -lboost_filesystem -lboost_program_options
OBJDIR_RELEASE = obj
DEP_RELEASE = 
OUT_RELEASE = build/SearchInFile

OBJ_RELEASE = $(OBJDIR_RELEASE)/src/main.o $(OBJDIR_RELEASE)/src/parse_arguments.o $(OBJDIR_RELEASE)/src/search.o

all: release

clean: clean_release

before_release: 
	test -d build || mkdir -p build
	test -d $(OBJDIR_RELEASE)/src || mkdir -p $(OBJDIR_RELEASE)/src

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/src/main.o: src/main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/main.cpp -o $(OBJDIR_RELEASE)/src/main.o

$(OBJDIR_RELEASE)/src/parse_arguments.o: src/parse_arguments.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/parse_arguments.cpp -o $(OBJDIR_RELEASE)/src/parse_arguments.o

$(OBJDIR_RELEASE)/src/search.o: src/search.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/search.cpp -o $(OBJDIR_RELEASE)/src/search.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf build
	rm -rf $(OBJDIR_RELEASE)/src

.PHONY: before_release after_release clean_release

